In [50]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder


In [51]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [52]:
df.shape

(569, 33)

In [53]:
df.drop(columns=['id','Unnamed: 32'], inplace= True)

In [54]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

# train test split

In [55]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:,0], test_size=0.2)

# scaling

In [56]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [57]:
x_train

array([[-1.03388963, -0.17111165, -1.03638305, ..., -0.7553962 ,
        -1.09385058, -0.32800317],
       [ 1.78859714, -0.36258838,  1.64697976, ...,  1.08180552,
        -0.23299908,  0.26806063],
       [-0.1154614 ,  0.66773875, -0.07055122, ...,  0.79721579,
         0.2960158 ,  0.51042243],
       ...,
       [-0.2750663 , -0.44009086, -0.33466173, ..., -0.99250358,
        -0.2057468 , -0.69014005],
       [-0.55227482, -0.30560126, -0.57114222, ..., -0.40521387,
         0.51724021, -0.53718783],
       [-0.42907104, -0.27140899, -0.39317237, ...,  0.39239831,
         0.53647711,  1.0710598 ]])

In [58]:
y_train

303    B
1      M
196    M
140    B
274    M
      ..
280    M
295    B
246    B
367    B
496    B
Name: diagnosis, Length: 455, dtype: object

# Label Encoding

In [59]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [60]:
y_train

array([0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,

# Numpy arrays to pytorch tensors

In [61]:
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [62]:
x_train_tensor

tensor([[-1.0339, -0.1711, -1.0364,  ..., -0.7554, -1.0939, -0.3280],
        [ 1.7886, -0.3626,  1.6470,  ...,  1.0818, -0.2330,  0.2681],
        [-0.1155,  0.6677, -0.0706,  ...,  0.7972,  0.2960,  0.5104],
        ...,
        [-0.2751, -0.4401, -0.3347,  ..., -0.9925, -0.2057, -0.6901],
        [-0.5523, -0.3056, -0.5711,  ..., -0.4052,  0.5172, -0.5372],
        [-0.4291, -0.2714, -0.3932,  ...,  0.3924,  0.5365,  1.0711]],
       dtype=torch.float64)

In [63]:
x_train_tensor.shape

torch.Size([455, 30])

# Defining the model

In [68]:
class MySimpleNN():

  def __init__(self,x):

    self.weights = torch.rand(x.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, x):
    z = torch.matmul(x, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

# important parameters

In [75]:
learning_rate = 0.1
epochs = 25

# Training pipeline

In [76]:
# create model

model = MySimpleNN(x_train_tensor)

# define loop
for epoch in range(epochs):


  # forward pass
  y_pred = model.forward(x_train_tensor)
  # print(y_pred)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)
  print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch+1}, Loss: {loss.item()}')


Epoch: 1, Loss: 3.4791933021213293
Epoch: 1, Loss: 3.4791933021213293
Epoch: 2, Loss: 3.337832226677566
Epoch: 2, Loss: 3.337832226677566
Epoch: 3, Loss: 3.191173629856481
Epoch: 3, Loss: 3.191173629856481
Epoch: 4, Loss: 3.0377258348232465
Epoch: 4, Loss: 3.0377258348232465
Epoch: 5, Loss: 2.8779721660031212
Epoch: 5, Loss: 2.8779721660031212
Epoch: 6, Loss: 2.713319344656993
Epoch: 6, Loss: 2.713319344656993
Epoch: 7, Loss: 2.542023316989641
Epoch: 7, Loss: 2.542023316989641
Epoch: 8, Loss: 2.367848966963435
Epoch: 8, Loss: 2.367848966963435
Epoch: 9, Loss: 2.1943005380437413
Epoch: 9, Loss: 2.1943005380437413
Epoch: 10, Loss: 2.0247403419170245
Epoch: 10, Loss: 2.0247403419170245
Epoch: 11, Loss: 1.8627857788715292
Epoch: 11, Loss: 1.8627857788715292
Epoch: 12, Loss: 1.709716023299061
Epoch: 12, Loss: 1.709716023299061
Epoch: 13, Loss: 1.5630313905883764
Epoch: 13, Loss: 1.5630313905883764
Epoch: 14, Loss: 1.4232314175893401
Epoch: 14, Loss: 1.4232314175893401
Epoch: 15, Loss: 1.294

In [78]:
model.weights

tensor([[ 0.4834],
        [ 0.4938],
        [-0.3888],
        [-0.1538],
        [ 0.0936],
        [-0.0959],
        [-0.4531],
        [ 0.2173],
        [ 0.0684],
        [ 0.1043],
        [ 0.2879],
        [ 0.2578],
        [ 0.1468],
        [ 0.0204],
        [ 0.2252],
        [-0.0604],
        [ 0.4248],
        [-0.3296],
        [ 0.1268],
        [-0.2519],
        [ 0.3945],
        [ 0.0501],
        [-0.4421],
        [ 0.2280],
        [ 0.3465],
        [ 0.0195],
        [-0.0193],
        [-0.3656],
        [-0.0400],
        [ 0.0061]], dtype=torch.float64, requires_grad=True)

In [79]:
model.bias

tensor([-0.1530], dtype=torch.float64, requires_grad=True)

# Evaluation

In [84]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(x_test_tensor)
  y_pred = (y_pred > 0.5).float()

  # calculate accuracy
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5147737860679626
