In [ ]:
import torch
print(torch.__version__)

2.8.0+cu126


In [ ]:
if torch.cuda.is_available():
  print("GPU is available!")
  print(f"Usinf GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available. using CPU.")

GPU is available!
Usinf GPU: Tesla T4


###Creating a Tensor

In [ ]:
# using empty

a = torch.empty(2,3)  # two dimension matrices -> ye sirf address asing kar deti h koi value nhi deti h
a


tensor([[-6.5809e-05,  4.3548e-41, -6.4038e-05],
        [ 4.3548e-41, -6.5841e-05,  4.3548e-41]])

In [ ]:
# check type

type(a)

torch.Tensor

In [ ]:
# using zeros

torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# using ones

torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# using rand

torch.rand(2,3)

tensor([[0.3818, 0.3478, 0.4109],
        [0.5698, 0.1220, 0.9394]])

In [ ]:
# use of seed

torch.rand(2,3)

tensor([[0.2208, 0.8282, 0.7290],
        [0.3152, 0.8244, 0.1386]])

In [ ]:
# manual_seed

torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# using tensor

torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# other ways

# arange
print("using arange ->",torch.arange(1,10,2))

#using linspace
print("using linspace ->",torch.linspace(1,10,10)) # 0 se 10 ke beech 10 equally spaced values generate karta hai.

# using eye
print("using eye ->",torch.eye(5)) # ye identity matric banata h

#using full.
print("using full ->",torch.full((3,3),5))  # Ek 3×3 (matrix / tensor) banao jisme har jagah pe value 5 ho.


using arange -> tensor([1, 3, 5, 7, 9])
using linspace -> tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


### Tensor Shapes

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)  # iska matlab h ki same shape h tensor bana sakte h but value alag hogi

tensor([[133478094011792,       868888336,       795416992],
        [      868888016,               0,       860684032]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x) # ye isliye generate nhi kar pa raha h kyuki ye float value generate karta h or original x me integer h isliye isko btana padhega


NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

In [ ]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

### Tensor Data Types

In [ ]:
# find data type

x.dtype

torch.int64

In [ ]:
# assign data type

torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
# using to()

x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

# Mathematical operation

### 1.Scalar operation

In [ ]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [ ]:
# addition

x+2

# substraction

x-2

# multiplication

x*2

# division

x/3

# int division

(x*100)//3

# mod

((x*100)//3)%2

# power

x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

### 2. Element wise operation

In [ ]:
a = torch.rand(2,2)
b = torch.rand(2,2)

print(a)
print(b)

tensor([[0.9969, 0.7565],
        [0.2239, 0.3023]])
tensor([[0.1784, 0.8238],
        [0.5557, 0.9770]])


In [ ]:
# addition

a+b

# substraction

a-b

# multiplication

a*b

# division

a/b

# mod

a%b

# power

a**b

tensor([[0.9994, 0.7946],
        [0.4353, 0.3108]])

In [ ]:
c = torch.tensor([1,-2,3,-4])

In [ ]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d = torch.tensor([4.9,2.3,3.7,4.4])

In [ ]:
# round
torch.round(d)

tensor([5., 2., 4., 4.])

In [ ]:
# ceil
torch.ceil(d)

tensor([5., 3., 4., 5.])

In [ ]:
# floor
torch.floor(d)

tensor([4., 2., 3., 4.])

In [ ]:
# clamp
torch.clamp(d,min=2,max=3)

tensor([3.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [ ]:
e = torch.randint(size=(2,3),low=0,high=10, dtype=torch.float32)
e

tensor([[0., 1., 9.],
        [9., 8., 0.]])

In [ ]:
# sum
torch.sum(e)

# sum along columns
torch.sum(e,dim=0)
# sum along rows
torch.sum(e,dim=1)

tensor([10., 17.])

In [ ]:
#mean
torch.mean(e)

tensor(4.5000)

In [ ]:
# mean along col
torch.mean(e,dim=0)

tensor([4.5000, 4.5000, 4.5000])

In [ ]:
# meadian
torch.median(e)

tensor(1.)

In [ ]:
# max amd min
torch.max(e)
torch.min(e)

tensor(0.)

In [ ]:
# product
torch.prod(e)

tensor(0.)

In [ ]:
# standard deviation
torch.std(e)

tensor(4.5935)

In [ ]:
# variance
torch.var(e)

tensor(21.1000)

In [ ]:
# argmax
torch.argmax(e)  # ye sabse max value ki position btata h

tensor(2)

In [ ]:
# argmin
torch.argmin(e)  # ye sabse min value ki position btata h

tensor(0)

### 4. Matrix operation

In [ ]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[7, 0, 0],
        [9, 5, 7]])
tensor([[3, 9],
        [4, 0],
        [5, 7]])


In [ ]:
# matrix multiplication
torch.matmul(f,g)

tensor([[ 21,  63],
        [ 82, 130]])

In [ ]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

# dot product
torch.dot(vector1,vector2)

tensor(11)

In [ ]:
# transpose
torch.transpose(f,0,1)

tensor([[7, 9],
        [0, 5],
        [0, 7]])

In [ ]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[5., 9., 9.],
        [7., 5., 9.],
        [8., 9., 7.]])

In [ ]:
# determinant
torch.det(h)

tensor(184.0000)

In [ ]:
# inverse
torch.inverse(h)

tensor([[-0.2500,  0.0978,  0.1957],
        [ 0.1250, -0.2011,  0.0978],
        [ 0.1250,  0.1467, -0.2065]])

### 5.comparison operation

In [ ]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[9, 2, 6],
        [7, 7, 8]])
tensor([[3, 6, 1],
        [5, 5, 0]])


In [ ]:
# greater than
i>j
# less than
i<j
# equal to
i == j
# not equal to
i != j
# greater than equal to


# less than equal to

tensor([[True, True, True],
        [True, True, True]])

### 6. Special function

In [ ]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[4., 3., 8.],
        [8., 3., 3.]])

In [ ]:
# log
torch.log(k)

tensor([[1.3863, 1.0986, 2.0794],
        [2.0794, 1.0986, 1.0986]])

In [ ]:
# exp
torch.exp(k)

tensor([[  54.5981,   20.0855, 2980.9580],
        [2980.9580,   20.0855,   20.0855]])

In [ ]:
# sqrt
torch.sqrt(k)

tensor([[2.0000, 1.7321, 2.8284],
        [2.8284, 1.7321, 1.7321]])

In [ ]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9820, 0.9526, 0.9997],
        [0.9997, 0.9526, 0.9526]])

In [ ]:
# softmax
torch.softmax(k,dim=0)

tensor([[0.0180, 0.5000, 0.9933],
        [0.9820, 0.5000, 0.0067]])

In [ ]:
# relu
torch.relu(k) # Agar value negative hai → usse 0 bana dega.
              # Agar value positive ya 0 hai → wahi value wapas dega.

tensor([[4., 3., 8.],
        [8., 3., 3.]])

# Inplace Operations
- inplace operator ka kaam h jaise ham kisi do chij ko add karte h toh uska result new tensor me aata h but inplace ye extra tensor ko bachata h

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.2170, 0.9454, 0.7116],
        [0.1157, 0.6574, 0.3451]])
tensor([[0.0453, 0.9798, 0.5548],
        [0.6868, 0.4920, 0.0748]])


In [ ]:
m+n

tensor([[0.2624, 1.9251, 1.2663],
        [0.8025, 1.1494, 0.4199]])

In [ ]:
m.add_(n)

tensor([[0.2624, 1.9251, 1.2663],
        [0.8025, 1.1494, 0.4199]])

In [ ]:
m

tensor([[0.2624, 1.9251, 1.2663],
        [0.8025, 1.1494, 0.4199]])

In [ ]:
n

tensor([[0.0453, 0.9798, 0.5548],
        [0.6868, 0.4920, 0.0748]])

In [ ]:
torch.relu(m)

tensor([[0.2624, 1.9251, 1.2663],
        [0.8025, 1.1494, 0.4199]])

In [ ]:
m.relu_()

tensor([[0.2624, 1.9251, 1.2663],
        [0.8025, 1.1494, 0.4199]])

In [ ]:
m

tensor([[0.2624, 1.9251, 1.2663],
        [0.8025, 1.1494, 0.4199]])

# Copying a Tensor

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.4655, 0.7110, 0.6415],
        [0.7189, 0.9263, 0.0460]])

In [ ]:
b = a

In [ ]:
b

tensor([[0.9605, 0.3271, 0.0103],
        [0.9516, 0.2855, 0.2324]])

In [ ]:
a[0][0] = 0

In [ ]:
a

tensor([[0.0000, 0.3271, 0.0103],
        [0.9516, 0.2855, 0.2324]])

In [ ]:
b

tensor([[0.0000, 0.3271, 0.0103],
        [0.9516, 0.2855, 0.2324]])

In [ ]:
id(a)

133473719179040

In [ ]:
id(b)

133473719179040

In [ ]:
b = a.clone()

In [ ]:
a

tensor([[0.0000, 0.3271, 0.0103],
        [0.9516, 0.2855, 0.2324]])

In [ ]:
b

tensor([[0.0000, 0.3271, 0.0103],
        [0.9516, 0.2855, 0.2324]])

In [ ]:
a[0][0] = 10

In [ ]:
a

tensor([[10.0000,  0.3271,  0.0103],
        [ 0.9516,  0.2855,  0.2324]])

In [ ]:
b

tensor([[0.0000, 0.3271, 0.0103],
        [0.9516, 0.2855, 0.2324]])

In [ ]:
id(a)

133473719179040

In [ ]:
id(b)

133473719160736

# Tensor Operation on GPU

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = torch.device('cuda')

In [ ]:
# creating a new tensor on GPU

torch.rand((2,3),device=device)

tensor([[0.3776, 0.3927, 0.6138],
        [0.4521, 0.3123, 0.0288]], device='cuda:0')

In [ ]:
# moving an existing tensor to GPU
a

tensor([[0.4655, 0.7110, 0.6415],
        [0.7189, 0.9263, 0.0460]])

In [ ]:
b = a.to(device)
b

tensor([[0.4655, 0.7110, 0.6415],
        [0.7189, 0.9263, 0.0460]], device='cuda:0')

In [ ]:
b+5

tensor([[5.4655, 5.7110, 5.6415],
        [5.7189, 5.9263, 5.0460]], device='cuda:0')

# Reshaping Tensors

In [ ]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b = torch.rand(2,3,4)
b

tensor([[[0.4501, 0.6531, 0.7013, 0.0888],
         [0.8981, 0.6605, 0.8692, 0.1160],
         [0.8796, 0.8118, 0.5598, 0.8951]],

        [[0.2645, 0.5064, 0.5538, 0.2778],
         [0.1483, 0.3494, 0.6351, 0.6044],
         [0.8513, 0.2092, 0.7257, 0.3001]]])

In [ ]:
# permute
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [ ]:
# unsqueeze
# image size
c = torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [ ]:
# squeeze
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

# NumPy and PyTorch

In [ ]:
import numpy as np

In [ ]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [ ]:
b = a.numpy()
b

array([1, 2, 3])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [ ]:
torch.from_numpy(c)

tensor([1, 2, 3])